//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollApplication.OurModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDays_Employees
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AttendanceID { get; set; }
        public Nullable<System.DateTime> AttendTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
    
        public virtual AttendanceDay AttendanceDay { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
