//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollApplication.OurModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Informations
    {
        public int ID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> EmployeeInformationID { get; set; }
        public Nullable<int> SalaryInformationID { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual SalaryInformation SalaryInformation { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SalaryInformation SalaryInformation1 { get; set; }
    }
}
