//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollApplication.OurModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Have_Login_Program
    {
        public int ID { get; set; }
        public Nullable<int> EmployeesID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
