//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollApplication.OurModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTractSalary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubTractSalary()
        {
            this.SalaryInformation_SubTrack = new HashSet<SalaryInformation_SubTrack>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Justification { get; set; }
        public Nullable<int> SanctionsID { get; set; }
        public Nullable<int> IDSalaryInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryInformation_SubTrack> SalaryInformation_SubTrack { get; set; }
        public virtual Sanctions_List Sanctions_List { get; set; }
    }
}
